language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - DJANGO='django>=1.7,<1.8'
  - DJANGO='django>=1.8,<1.9'
  - DJANGO='django>=1.9,<1.10'
  - DJANGO='django>=1.10,<1.11'

install:
  - pip install -r test_requirements.txt
  - pip install $DJANGO

script: python manage.py test

sudo: false

notifications:
  email: false

matrix:
  exclude:
    - python: 3.5
      env: DJANGO='django>=1.7,<1.8'
  allow_failures:
    - python: 2.7
      env: DJANGO='django>=1.7,<1.8'
    - python: 2.7
      env: DJANGO='django>=1.8,<1.9'
    - python: 2.7
      env: DJANGO='django>=1.9,<1.10'
    - python: 2.7
      env: DJANGO='django>=1.10,<1.11'
    - python: 3.3
      env: DJANGO='django>=1.7,<1.8'
    - python: 3.3
      env: DJANGO='django>=1.8,<1.9'
    - python: 3.3
      env: DJANGO='django>=1.9,<1.10'
    - python: 3.3
      env: DJANGO='django>=1.10,<1.11'
